// @flow

export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS';
export const GET_USER_BY_ID_FAILURE = 'GET_USER_BY_ID_FAILURE';

export const GET_USER_FEED = 'GET_USER_FEED';
export const GET_USER_FEED_SUCCESS = 'GET_USER_FEED_SUCCESS';
export const GET_USER_FEED_FAILURE = 'GET_USER_FEED_FAILURE';
