// @flow

export const GET_LOGIN_VERIFICATION = 'GET_LOGIN_VERIFICATION';
export const GET_LOGIN_VERIFICATION_SUCCESS = 'GET_LOGIN_VERIFICATION_SUCCESS';
export const GET_LOGIN_VERIFICATION_FAILURE = 'GET_LOGIN_VERIFICATION_FAILURE';
